export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const GOOGLE_APP_REDIRECT_URL = 'GOOGLE_APP_REDIRECT_URL';
export const FRONTEND_URL = 'FRONTEND_URL';
export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME =
  'JWT_ACCESS_TOKEN_EXPIRATION_TIME';

export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME =
  'JWT_REFRESH_TOKEN_EXPIRATION_TIME';

export const FACEBOOK_APP_ID = 'FACEBOOK_APP_ID';
export const FACEBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET';
export const FACEBOOK_APP_REDIRECT_URL = 'FACEBOOK_APP_REDIRECT_URL';

export const EMAIL_EXPIRY_TIME = 'EMAIL_EXPIRY_TIME';

export const STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY';
export const STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET';

export const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';
export const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';
export const CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME';
export const DRIVER_CLOUDINARY_FOLDER_NAME = 'DRIVER_CLOUDINARY_FOLDER_NAME';

export const JWT_EMAIL_SECRET = 'JWT_EMAIL_SECRET';

export const SUCCESS_URL = 'SUCCESS_URL';
export const CANCEL_URL = 'CANCEL_URL';
